import Header from '@/components/Header';
import '../styles/index.scss';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Providers from '@/components/Providers';
import Footer from '@/components/Footer';

const mainFont = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Products app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={mainFont.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
